version: '3'

networks:
  nets:

services:
  chika:
    build: .
    volumes:
      - ./database:/database
      - /etc/ssl/certs:/etc/ssl/certs
    env_file:
      - .env
    restart: on-failure
    networks:
      - nets
